export const timezoneOptions = [
    {
        label: "Africa",
        items: [
            { name: "Africa/Abidjan", value: "Africa/Abidjan%GMT0" },
            { name: "Africa/Accra", value: "Africa/Accra%GMT0" },
            { name: "Africa/Addis_Ababa", value: "Africa/Addis_Ababa%EAT-3" },
            { name: "Africa/Algiers", value: "Africa/Algiers%CET-1" },
            { name: "Africa/Asmara", value: "Africa/Asmara%EAT-3" },
            { name: "Africa/Bamako", value: "Africa/Bamako%GMT0" },
            { name: "Africa/Bangui", value: "Africa/Bangui%WAT-1" },
            { name: "Africa/Banjul", value: "Africa/Banjul%GMT0" },
            { name: "Africa/Bissau", value: "Africa/Bissau%GMT0" },
            { name: "Africa/Blantyre", value: "Africa/Blantyre%CAT-2" },
            { name: "Africa/Brazzaville", value: "Africa/Brazzaville%WAT-1" },
            { name: "Africa/Bujumbura", value: "Africa/Bujumbura%CAT-2" },
            { name: "Africa/Cairo", value: "Africa/Cairo%EET-2" },
            { name: "Africa/Casablanca", value: "Africa/Casablanca%<+01>-1" },
            { name: "Africa/Ceuta", value: "Africa/Ceuta%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Africa/Conakry", value: "Africa/Conakry%GMT0" },
            { name: "Africa/Dakar", value: "Africa/Dakar%GMT0" },
            { name: "Africa/Dar_es_Salaam", value: "Africa/Dar_es_Salaam%EAT-3" },
            { name: "Africa/Djibouti", value: "Africa/Djibouti%EAT-3" },
            { name: "Africa/Douala", value: "Africa/Douala%WAT-1" },
            { name: "Africa/El_Aaiun", value: "Africa/El_Aaiun%<+01>-1" },
            { name: "Africa/Freetown", value: "Africa/Freetown%GMT0" },
            { name: "Africa/Gaborone", value: "Africa/Gaborone%CAT-2" },
            { name: "Africa/Harare", value: "Africa/Harare%CAT-2" },
            { name: "Africa/Johannesburg", value: "Africa/Johannesburg%SAST-2" },
            { name: "Africa/Juba", value: "Africa/Juba%CAT-2" },
            { name: "Africa/Kampala", value: "Africa/Kampala%EAT-3" },
            { name: "Africa/Khartoum", value: "Africa/Khartoum%CAT-2" },
            { name: "Africa/Kigali", value: "Africa/Kigali%CAT-2" },
            { name: "Africa/Kinshasa", value: "Africa/Kinshasa%WAT-1" },
            { name: "Africa/Lagos", value: "Africa/Lagos%WAT-1" },
            { name: "Africa/Libreville", value: "Africa/Libreville%WAT-1" },
            { name: "Africa/Lome", value: "Africa/Lome%GMT0" },
            { name: "Africa/Luanda", value: "Africa/Luanda%WAT-1" },
            { name: "Africa/Lubumbashi", value: "Africa/Lubumbashi%CAT-2" },
            { name: "Africa/Lusaka", value: "Africa/Lusaka%CAT-2" },
            { name: "Africa/Malabo", value: "Africa/Malabo%WAT-1" },
            { name: "Africa/Maputo", value: "Africa/Maputo%CAT-2" },
            { name: "Africa/Maseru", value: "Africa/Maseru%SAST-2" },
            { name: "Africa/Mbabane", value: "Africa/Mbabane%SAST-2" },
            { name: "Africa/Mogadishu", value: "Africa/Mogadishu%EAT-3" },
            { name: "Africa/Monrovia", value: "Africa/Monrovia%GMT0" },
            { name: "Africa/Nairobi", value: "Africa/Nairobi%EAT-3" },
            { name: "Africa/Ndjamena", value: "Africa/Ndjamena%WAT-1" },
            { name: "Africa/Niamey", value: "Africa/Niamey%WAT-1" },
            { name: "Africa/Nouakchott", value: "Africa/Nouakchott%GMT0" },
            { name: "Africa/Ouagadougou", value: "Africa/Ouagadougou%GMT0" },
            { name: "Africa/Porto-Novo", value: "Africa/Porto-Novo%WAT-1" },
            { name: "Africa/Sao_Tome", value: "Africa/Sao_Tome%GMT0" },
            { name: "Africa/Tripoli", value: "Africa/Tripoli%EET-2" },
            { name: "Africa/Tunis", value: "Africa/Tunis%CET-1" },
            { name: "Africa/Windhoek", value: "Africa/Windhoek%CAT-2" },
        ]
    },
    {
        label: "America",
        items: [
            { name: "America/Adak", value: "America/Adak%HST10HDT,M3.2.0,M11.1.0" },
            { name: "America/Anchorage", value: "America/Anchorage%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/Anguilla", value: "America/Anguilla%AST4" },
            { name: "America/Antigua", value: "America/Antigua%AST4" },
            { name: "America/Araguaina", value: "America/Araguaina%<-03>3" },
            { name: "America/Argentina/Buenos_Aires", value: "America/Argentina/Buenos_Aires%<-03>3" },
            { name: "America/Argentina/Catamarca", value: "America/Argentina/Catamarca%<-03>3" },
            { name: "America/Argentina/Cordoba", value: "America/Argentina/Cordoba%<-03>3" },
            { name: "America/Argentina/Jujuy", value: "America/Argentina/Jujuy%<-03>3" },
            { name: "America/Argentina/La_Rioja", value: "America/Argentina/La_Rioja%<-03>3" },
            { name: "America/Argentina/Mendoza", value: "America/Argentina/Mendoza%<-03>3" },
            { name: "America/Argentina/Rio_Gallegos", value: "America/Argentina/Rio_Gallegos%<-03>3" },
            { name: "America/Argentina/Salta", value: "America/Argentina/Salta%<-03>3" },
            { name: "America/Argentina/San_Juan", value: "America/Argentina/San_Juan%<-03>3" },
            { name: "America/Argentina/San_Luis", value: "America/Argentina/San_Luis%<-03>3" },
            { name: "America/Argentina/Tucuman", value: "America/Argentina/Tucuman%<-03>3" },
            { name: "America/Argentina/Ushuaia", value: "America/Argentina/Ushuaia%<-03>3" },
            { name: "America/Aruba", value: "America/Aruba%AST4" },
            { name: "America/Asuncion", value: "America/Asuncion%<-04>4<-03>,M10.1.0/0,M3.4.0/0" },
            { name: "America/Atikokan", value: "America/Atikokan%EST5" },
            { name: "America/Bahia", value: "America/Bahia%<-03>3" },
            { name: "America/Bahia_Banderas", value: "America/Bahia_Banderas%CST6" },
            { name: "America/Barbados", value: "America/Barbados%AST4" },
            { name: "America/Belem", value: "America/Belem%<-03>3" },
            { name: "America/Belize", value: "America/Belize%CST6" },
            { name: "America/Blanc-Sablon", value: "America/Blanc-Sablon%AST4" },
            { name: "America/Boa_Vista", value: "America/Boa_Vista%<-04>4" },
            { name: "America/Bogota", value: "America/Bogota%<-05>5" },
            { name: "America/Boise", value: "America/Boise%MST7MDT,M3.2.0,M11.1.0" },
            { name: "America/Cambridge_Bay", value: "America/Cambridge_Bay%MST7MDT,M3.2.0,M11.1.0" },
            { name: "America/Campo_Grande", value: "America/Campo_Grande%<-04>4" },
            { name: "America/Cancun", value: "America/Cancun%EST5" },
            { name: "America/Caracas", value: "America/Caracas%<-04>4" },
            { name: "America/Cayenne", value: "America/Cayenne%<-03>3" },
            { name: "America/Cayman", value: "America/Cayman%EST5" },
            { name: "America/Chicago", value: "America/Chicago%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Chihuahua", value: "America/Chihuahua%CST6" },
            { name: "America/Costa_Rica", value: "America/Costa_Rica%CST6" },
            { name: "America/Creston", value: "America/Creston%MST7" },
            { name: "America/Cuiaba", value: "America/Cuiaba%<-04>4" },
            { name: "America/Curacao", value: "America/Curacao%AST4" },
            { name: "America/Danmarkshavn", value: "America/Danmarkshavn%GMT0" },
            { name: "America/Dawson", value: "America/Dawson%MST7" },
            { name: "America/Dawson_Creek", value: "America/Dawson_Creek%MST7" },
            { name: "America/Denver", value: "America/Denver%MST7MDT,M3.2.0,M11.1.0" },
            { name: "America/Detroit", value: "America/Detroit%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Dominica", value: "America/Dominica%AST4" },
            { name: "America/Edmonton", value: "America/Edmonton%MST7MDT,M3.2.0,M11.1.0" },
            { name: "America/Eirunepe", value: "America/Eirunepe%<-05>5" },
            { name: "America/El_Salvador", value: "America/El_Salvador%CST6" },
            { name: "America/Fortaleza", value: "America/Fortaleza%<-03>3" },
            { name: "America/Fort_Nelson", value: "America/Fort_Nelson%MST7" },
            { name: "America/Glace_Bay", value: "America/Glace_Bay%AST4ADT,M3.2.0,M11.1.0" },
            { name: "America/Godthab", value: "America/Godthab%<-02>2" },
            { name: "America/Goose_Bay", value: "America/Goose_Bay%AST4ADT,M3.2.0,M11.1.0" },
            { name: "America/Grand_Turk", value: "America/Grand_Turk%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Grenada", value: "America/Grenada%AST4" },
            { name: "America/Guadeloupe", value: "America/Guadeloupe%AST4" },
            { name: "America/Guatemala", value: "America/Guatemala%CST6" },
            { name: "America/Guayaquil", value: "America/Guayaquil%<-05>5" },
            { name: "America/Guyana", value: "America/Guyana%<-04>4" },
            { name: "America/Halifax", value: "America/Halifax%AST4ADT,M3.2.0,M11.1.0" },
            { name: "America/Havana", value: "America/Havana%CST5CDT,M3.2.0/0,M11.1.0/1" },
            { name: "America/Hermosillo", value: "America/Hermosillo%MST7" },
            { name: "America/Indiana/Indianapolis", value: "America/Indiana/Indianapolis%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Knox", value: "America/Indiana/Knox%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Marengo", value: "America/Indiana/Marengo%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Petersburg", value: "America/Indiana/Petersburg%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Tell_City", value: "America/Indiana/Tell_City%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Vevay", value: "America/Indiana/Vevay%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Vincennes", value: "America/Indiana/Vincennes%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Indiana/Winamac", value: "America/Indiana/Winamac%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Inuvik", value: "America/Inuvik%MST7MDT,M3.2.0,M11.1.0" },
            { name: "America/Iqaluit", value: "America/Iqaluit%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Jamaica", value: "America/Jamaica%EST5" },
            { name: "America/Juneau", value: "America/Juneau%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/Kentucky/Louisville", value: "America/Kentucky/Louisville%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Kentucky/Monticello", value: "America/Kentucky/Monticello%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Kralendijk", value: "America/Kralendijk%AST4" },
            { name: "America/La_Paz", value: "America/La_Paz%<-04>4" },
            { name: "America/Lima", value: "America/Lima%<-05>5" },
            { name: "America/Los_Angeles", value: "America/Los_Angeles%PST8PDT,M3.2.0,M11.1.0" },
            { name: "America/Lower_Princes", value: "America/Lower_Princes%AST4" },
            { name: "America/Maceio", value: "America/Maceio%<-03>3" },
            { name: "America/Managua", value: "America/Managua%CST6" },
            { name: "America/Manaus", value: "America/Manaus%<-04>4" },
            { name: "America/Marigot", value: "America/Marigot%AST4" },
            { name: "America/Martinique", value: "America/Martinique%AST4" },
            { name: "America/Matamoros", value: "America/Matamoros%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Mazatlan", value: "America/Mazatlan%MST7" },
            { name: "America/Menominee", value: "America/Menominee%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Merida", value: "America/Merida%CST6" },
            { name: "America/Metlakatla", value: "America/Metlakatla%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/Mexico_City", value: "America/Mexico_City%CST6" },
            { name: "America/Miquelon", value: "America/Miquelon%<-03>3<-02>,M3.2.0,M11.1.0" },
            { name: "America/Moncton", value: "America/Moncton%AST4ADT,M3.2.0,M11.1.0" },
            { name: "America/Monterrey", value: "America/Monterrey%CST6" },
            { name: "America/Montevideo", value: "America/Montevideo%<-03>3" },
            { name: "America/Montreal", value: "America/Montreal%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Montserrat", value: "America/Montserrat%AST4" },
            { name: "America/Nassau", value: "America/Nassau%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/New_York", value: "America/New_York%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Nipigon", value: "America/Nipigon%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Nome", value: "America/Nome%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/Noronha", value: "America/Noronha%<-02>2" },
            { name: "America/North_Dakota/Beulah", value: "America/North_Dakota/Beulah%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/North_Dakota/Center", value: "America/North_Dakota/Center%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/North_Dakota/New_Salem", value: "America/North_Dakota/New_Salem%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Nuuk", value: "America/Nuuk%<-02>2" },
            { name: "America/Ojinaga", value: "America/Ojinaga%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Panama", value: "America/Panama%EST5" },
            { name: "America/Pangnirtung", value: "America/Pangnirtung%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Paramaribo", value: "America/Paramaribo%<-03>3" },
            { name: "America/Phoenix", value: "America/Phoenix%MST7" },
            { name: "America/Port-au-Prince", value: "America/Port-au-Prince%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Port_of_Spain", value: "America/Port_of_Spain%AST4" },
            { name: "America/Porto_Velho", value: "America/Porto_Velho%<-04>4" },
            { name: "America/Puerto_Rico", value: "America/Puerto_Rico%AST4" },
            { name: "America/Punta_Arenas", value: "America/Punta_Arenas%<-03>3" },
            { name: "America/Rainy_River", value: "America/Rainy_River%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Rankin_Inlet", value: "America/Rankin_Inlet%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Recife", value: "America/Recife%<-03>3" },
            { name: "America/Regina", value: "America/Regina%CST6" },
            { name: "America/Resolute", value: "America/Resolute%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Rio_Branco", value: "America/Rio_Branco%<-05>5" },
            { name: "America/Santarem", value: "America/Santarem%<-03>3" },
            { name: "America/Santiago", value: "America/Santiago%<-04>4<-03>,M9.1.6/24,M4.1.6/24" },
            { name: "America/Santo_Domingo", value: "America/Santo_Domingo%AST4" },
            { name: "America/Sao_Paulo", value: "America/Sao_Paulo%<-03>3" },
            { name: "America/Scoresbysund", value: "America/Scoresbysund%<-01>1<+00>,M3.5.0/0,M10.5.0/1" },
            { name: "America/Sitka", value: "America/Sitka%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/St_Barthelemy", value: "America/St_Barthelemy%AST4" },
            { name: "America/St_Johns", value: "America/St_Johns%NST3:30NDT,M3.2.0,M11.1.0" },
            { name: "America/St_Kitts", value: "America/St_Kitts%AST4" },
            { name: "America/St_Lucia", value: "America/St_Lucia%AST4" },
            { name: "America/St_Thomas", value: "America/St_Thomas%AST4" },
            { name: "America/St_Vincent", value: "America/St_Vincent%AST4" },
            { name: "America/Swift_Current", value: "America/Swift_Current%CST6" },
            { name: "America/Tegucigalpa", value: "America/Tegucigalpa%CST6" },
            { name: "America/Thule", value: "America/Thule%AST4ADT,M3.2.0,M11.1.0" },
            { name: "America/Thunder_Bay", value: "America/Thunder_Bay%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Tijuana", value: "America/Tijuana%PST8PDT,M3.2.0,M11.1.0" },
            { name: "America/Toronto", value: "America/Toronto%EST5EDT,M3.2.0,M11.1.0" },
            { name: "America/Tortola", value: "America/Tortola%AST4" },
            { name: "America/Vancouver", value: "America/Vancouver%PST8PDT,M3.2.0,M11.1.0" },
            { name: "America/Whitehorse", value: "America/Whitehorse%MST7" },
            { name: "America/Winnipeg", value: "America/Winnipeg%CST6CDT,M3.2.0,M11.1.0" },
            { name: "America/Yakutat", value: "America/Yakutat%AKST9AKDT,M3.2.0,M11.1.0" },
            { name: "America/Yellowknife", value: "America/Yellowknife%MST7MDT,M3.2.0,M11.1.0" },
        ]
    },
    {
        label: "Antarctica",
        items: [
            { name: "Antarctica/Casey", value: "Antarctica/Casey%<+11>-11" },
            { name: "Antarctica/Davis", value: "Antarctica/Davis%<+07>-7" },
            { name: "Antarctica/DumontDUrville", value: "Antarctica/DumontDUrville%<+10>-10" },
            { name: "Antarctica/Macquarie", value: "Antarctica/Macquarie%AEST-10AEDT,M10.1.0,M4.1.0/3" },
            { name: "Antarctica/Mawson", value: "Antarctica/Mawson%<+05>-5" },
            { name: "Antarctica/McMurdo", value: "Antarctica/McMurdo%NZST-12NZDT,M9.5.0,M4.1.0/3" },
            { name: "Antarctica/Palmer", value: "Antarctica/Palmer%<-03>3" },
            { name: "Antarctica/Rothera", value: "Antarctica/Rothera%<-03>3" },
            { name: "Antarctica/Syowa", value: "Antarctica/Syowa%<+03>-3" },
            { name: "Antarctica/Troll", value: "Antarctica/Troll%<+00>0<+02>-2,M3.5.0/1,M10.5.0/3" },
            { name: "Antarctica/Vostok", value: "Antarctica/Vostok%<+06>-6" },
        ]
    },
    {
        label: "Arctic",
        items: [
            { name: "Arctic/Longyearbyen", value: "Arctic/Longyearbyen%CET-1CEST,M3.5.0,M10.5.0/3" },
        ]
    },
    {
        label: "Asia",
        items: [
            { name: "Asia/Aden", value: "Asia/Aden%<+03>-3" },
            { name: "Asia/Almaty", value: "Asia/Almaty%<+06>-6" },
            { name: "Asia/Amman", value: "Asia/Amman%<+03>-3" },
            { name: "Asia/Anadyr", value: "Asia/Anadyr%<+12>-12" },
            { name: "Asia/Aqtau", value: "Asia/Aqtau%<+05>-5" },
            { name: "Asia/Aqtobe", value: "Asia/Aqtobe%<+05>-5" },
            { name: "Asia/Ashgabat", value: "Asia/Ashgabat%<+05>-5" },
            { name: "Asia/Atyrau", value: "Asia/Atyrau%<+05>-5" },
            { name: "Asia/Baghdad", value: "Asia/Baghdad%<+03>-3" },
            { name: "Asia/Bahrain", value: "Asia/Bahrain%<+03>-3" },
            { name: "Asia/Baku", value: "Asia/Baku%<+04>-4" },
            { name: "Asia/Bangkok", value: "Asia/Bangkok%<+07>-7" },
            { name: "Asia/Barnaul", value: "Asia/Barnaul%<+07>-7" },
            { name: "Asia/Beirut", value: "Asia/Beirut%EET-2EEST,M3.5.0/0,M10.5.0/0" },
            { name: "Asia/Bishkek", value: "Asia/Bishkek%<+06>-6" },
            { name: "Asia/Brunei", value: "Asia/Brunei%<+08>-8" },
            { name: "Asia/Chita", value: "Asia/Chita%<+09>-9" },
            { name: "Asia/Choibalsan", value: "Asia/Choibalsan%<+08>-8" },
            { name: "Asia/Colombo", value: "Asia/Colombo%<+0530>-5:30" },
            { name: "Asia/Damascus", value: "Asia/Damascus%<+03>-3" },
            { name: "Asia/Dhaka", value: "Asia/Dhaka%<+06>-6" },
            { name: "Asia/Dili", value: "Asia/Dili%<+09>-9" },
            { name: "Asia/Dubai", value: "Asia/Dubai%<+04>-4" },
            { name: "Asia/Dushanbe", value: "Asia/Dushanbe%<+05>-5" },
            { name: "Asia/Famagusta", value: "Asia/Famagusta%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Asia/Gaza", value: "Asia/Gaza%EET-2EEST,M3.4.4/50,M10.4.4/50" },
            { name: "Asia/Hebron", value: "Asia/Hebron%EET-2EEST,M3.4.4/50,M10.4.4/50" },
            { name: "Asia/Ho_Chi_Minh", value: "Asia/Ho_Chi_Minh%<+07>-7" },
            { name: "Asia/Hong_Kong", value: "Asia/Hong_Kong%HKT-8" },
            { name: "Asia/Hovd", value: "Asia/Hovd%<+07>-7" },
            { name: "Asia/Irkutsk", value: "Asia/Irkutsk%<+08>-8" },
            { name: "Asia/Jakarta", value: "Asia/Jakarta%WIB-7" },
            { name: "Asia/Jayapura", value: "Asia/Jayapura%WIT-9" },
            { name: "Asia/Jerusalem", value: "Asia/Jerusalem%IST-2IDT,M3.4.4/26,M10.5.0" },
            { name: "Asia/Kabul", value: "Asia/Kabul%<+0430>-4:30" },
            { name: "Asia/Kamchatka", value: "Asia/Kamchatka%<+12>-12" },
            { name: "Asia/Karachi", value: "Asia/Karachi%PKT-5" },
            { name: "Asia/Kathmandu", value: "Asia/Kathmandu%<+0545>-5:45" },
            { name: "Asia/Khandyga", value: "Asia/Khandyga%<+09>-9" },
            { name: "Asia/Kolkata", value: "Asia/Kolkata%IST-5:30" },
            { name: "Asia/Krasnoyarsk", value: "Asia/Krasnoyarsk%<+07>-7" },
            { name: "Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur%<+08>-8" },
            { name: "Asia/Kuching", value: "Asia/Kuching%<+08>-8" },
            { name: "Asia/Kuwait", value: "Asia/Kuwait%<+03>-3" },
            { name: "Asia/Macau", value: "Asia/Macau%CST-8" },
            { name: "Asia/Magadan", value: "Asia/Magadan%<+11>-11" },
            { name: "Asia/Makassar", value: "Asia/Makassar%WITA-8" },
            { name: "Asia/Manila", value: "Asia/Manila%PST-8" },
            { name: "Asia/Muscat", value: "Asia/Muscat%<+04>-4" },
            { name: "Asia/Nicosia", value: "Asia/Nicosia%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Asia/Novokuznetsk", value: "Asia/Novokuznetsk%<+07>-7" },
            { name: "Asia/Novosibirsk", value: "Asia/Novosibirsk%<+07>-7" },
            { name: "Asia/Omsk", value: "Asia/Omsk%<+06>-6" },
            { name: "Asia/Oral", value: "Asia/Oral%<+05>-5" },
            { name: "Asia/Phnom_Penh", value: "Asia/Phnom_Penh%<+07>-7" },
            { name: "Asia/Pontianak", value: "Asia/Pontianak%WIB-7" },
            { name: "Asia/Pyongyang", value: "Asia/Pyongyang%KST-9" },
            { name: "Asia/Qatar", value: "Asia/Qatar%<+03>-3" },
            { name: "Asia/Qyzylorda", value: "Asia/Qyzylorda%<+05>-5" },
            { name: "Asia/Riyadh", value: "Asia/Riyadh%<+03>-3" },
            { name: "Asia/Sakhalin", value: "Asia/Sakhalin%<+11>-11" },
            { name: "Asia/Samarkand", value: "Asia/Samarkand%<+05>-5" },
            { name: "Asia/Seoul", value: "Asia/Seoul%KST-9" },
            { name: "Asia/Shanghai", value: "Asia/Shanghai%CST-8" },
            { name: "Asia/Singapore", value: "Asia/Singapore%<+08>-8" },
            { name: "Asia/Srednekolymsk", value: "Asia/Srednekolymsk%<+11>-11" },
            { name: "Asia/Taipei", value: "Asia/Taipei%CST-8" },
            { name: "Asia/Tashkent", value: "Asia/Tashkent%<+05>-5" },
            { name: "Asia/Tbilisi", value: "Asia/Tbilisi%<+04>-4" },
            { name: "Asia/Tehran", value: "Asia/Tehran%<+0330>-3:30" },
            { name: "Asia/Thimphu", value: "Asia/Thimphu%<+06>-6" },
            { name: "Asia/Tokyo", value: "Asia/Tokyo%JST-9" },
            { name: "Asia/Tomsk", value: "Asia/Tomsk%<+07>-7" },
            { name: "Asia/Ulaanbaatar", value: "Asia/Ulaanbaatar%<+08>-8" },
            { name: "Asia/Urumqi", value: "Asia/Urumqi%<+06>-6" },
            { name: "Asia/Ust-Nera", value: "Asia/Ust-Nera%<+10>-10" },
            { name: "Asia/Vientiane", value: "Asia/Vientiane%<+07>-7" },
            { name: "Asia/Vladivostok", value: "Asia/Vladivostok%<+10>-10" },
            { name: "Asia/Yakutsk", value: "Asia/Yakutsk%<+09>-9" },
            { name: "Asia/Yangon", value: "Asia/Yangon%<+0630>-6:30" },
            { name: "Asia/Yekaterinburg", value: "Asia/Yekaterinburg%<+05>-5" },
            { name: "Asia/Yerevan", value: "Asia/Yerevan%<+04>-4" },
        ]
    },
    {
        label: "Atlantic",
        items: [
            { name: "Atlantic/Azores", value: "Atlantic/Azores%<-01>1<+00>,M3.5.0/0,M10.5.0/1" },
            { name: "Atlantic/Bermuda", value: "Atlantic/Bermuda%AST4ADT,M3.2.0,M11.1.0" },
            { name: "Atlantic/Canary", value: "Atlantic/Canary%WET0WEST,M3.5.0/1,M10.5.0" },
            { name: "Atlantic/Cape_Verde", value: "Atlantic/Cape_Verde%<-01>1" },
            { name: "Atlantic/Faroe", value: "Atlantic/Faroe%WET0WEST,M3.5.0/1,M10.5.0" },
            { name: "Atlantic/Madeira", value: "Atlantic/Madeira%WET0WEST,M3.5.0/1,M10.5.0" },
            { name: "Atlantic/Reykjavik", value: "Atlantic/Reykjavik%GMT0" },
            { name: "Atlantic/South_Georgia", value: "Atlantic/South_Georgia%<-02>2" },
            { name: "Atlantic/Stanley", value: "Atlantic/Stanley%<-03>3" },
            { name: "Atlantic/St_Helena", value: "Atlantic/St_Helena%GMT0" },
        ]
    },
    {
        label: "Australia",
        items: [
            { name: "Australia/Adelaide", value: "Australia/Adelaide%ACST-9:30ACDT,M10.1.0,M4.1.0/3" },
            { name: "Australia/Brisbane", value: "Australia/Brisbane%AEST-10" },
            { name: "Australia/Broken_Hill", value: "Australia/Broken_Hill%ACST-9:30ACDT,M10.1.0,M4.1.0/3" },
            { name: "Australia/Currie", value: "Australia/Currie%AEST-10AEDT,M10.1.0,M4.1.0/3" },
            { name: "Australia/Darwin", value: "Australia/Darwin%ACST-9:30" },
            { name: "Australia/Eucla", value: "Australia/Eucla%<+0845>-8:45" },
            { name: "Australia/Hobart", value: "Australia/Hobart%AEST-10AEDT,M10.1.0,M4.1.0/3" },
            { name: "Australia/Lindeman", value: "Australia/Lindeman%AEST-10" },
            { name: "Australia/Lord_Howe", value: "Australia/Lord_Howe%<+1030>-10:30<+11>-11,M10.1.0,M4.1.0" },
            { name: "Australia/Melbourne", value: "Australia/Melbourne%AEST-10AEDT,M10.1.0,M4.1.0/3" },
            { name: "Australia/Perth", value: "Australia/Perth%AWST-8" },
            { name: "Australia/Sydney", value: "Australia/Sydney%AEST-10AEDT,M10.1.0,M4.1.0/3" },
        ]
    },
    {
        label: "Europe",
        items: [
            { name: "Europe/Amsterdam", value: "Europe/Amsterdam%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Andorra", value: "Europe/Andorra%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Astrakhan", value: "Europe/Astrakhan%<+04>-4" },
            { name: "Europe/Athens", value: "Europe/Athens%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Belgrade", value: "Europe/Belgrade%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Berlin", value: "Europe/Berlin%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Bratislava", value: "Europe/Bratislava%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Brussels", value: "Europe/Brussels%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Bucharest", value: "Europe/Bucharest%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Budapest", value: "Europe/Budapest%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Busingen", value: "Europe/Busingen%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Chisinau", value: "Europe/Chisinau%EET-2EEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Copenhagen", value: "Europe/Copenhagen%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Dublin", value: "Europe/Dublin%IST-1GMT0,M10.5.0,M3.5.0/1" },
            { name: "Europe/Gibraltar", value: "Europe/Gibraltar%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Guernsey", value: "Europe/Guernsey%GMT0BST,M3.5.0/1,M10.5.0" },
            { name: "Europe/Helsinki", value: "Europe/Helsinki%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Isle_of_Man", value: "Europe/Isle_of_Man%GMT0BST,M3.5.0/1,M10.5.0" },
            { name: "Europe/Istanbul", value: "Europe/Istanbul%<+03>-3" },
            { name: "Europe/Jersey", value: "Europe/Jersey%GMT0BST,M3.5.0/1,M10.5.0" },
            { name: "Europe/Kaliningrad", value: "Europe/Kaliningrad%EET-2" },
            { name: "Europe/Kiev", value: "Europe/Kiev%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Kirov", value: "Europe/Kirov%<+03>-3" },
            { name: "Europe/Lisbon", value: "Europe/Lisbon%WET0WEST,M3.5.0/1,M10.5.0" },
            { name: "Europe/Ljubljana", value: "Europe/Ljubljana%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/London", value: "Europe/London%GMT0BST,M3.5.0/1,M10.5.0" },
            { name: "Europe/Luxembourg", value: "Europe/Luxembourg%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Madrid", value: "Europe/Madrid%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Malta", value: "Europe/Malta%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Mariehamn", value: "Europe/Mariehamn%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Minsk", value: "Europe/Minsk%<+03>-3" },
            { name: "Europe/Monaco", value: "Europe/Monaco%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Moscow", value: "Europe/Moscow%MSK-3" },
            { name: "Europe/Oslo", value: "Europe/Oslo%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Paris", value: "Europe/Paris%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Podgorica", value: "Europe/Podgorica%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Prague", value: "Europe/Prague%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Riga", value: "Europe/Riga%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Rome", value: "Europe/Rome%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Samara", value: "Europe/Samara%<+04>-4" },
            { name: "Europe/San_Marino", value: "Europe/San_Marino%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Sarajevo", value: "Europe/Sarajevo%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Saratov", value: "Europe/Saratov%<+04>-4" },
            { name: "Europe/Simferopol", value: "Europe/Simferopol%MSK-3" },
            { name: "Europe/Skopje", value: "Europe/Skopje%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Sofia", value: "Europe/Sofia%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Stockholm", value: "Europe/Stockholm%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Tallinn", value: "Europe/Tallinn%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Tirane", value: "Europe/Tirane%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Ulyanovsk", value: "Europe/Ulyanovsk%<+04>-4" },
            { name: "Europe/Uzhgorod", value: "Europe/Uzhgorod%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Vaduz", value: "Europe/Vaduz%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Vatican", value: "Europe/Vatican%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Vienna", value: "Europe/Vienna%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Vilnius", value: "Europe/Vilnius%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Volgograd", value: "Europe/Volgograd%<+03>-3" },
            { name: "Europe/Warsaw", value: "Europe/Warsaw%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Zagreb", value: "Europe/Zagreb%CET-1CEST,M3.5.0,M10.5.0/3" },
            { name: "Europe/Zaporozhye", value: "Europe/Zaporozhye%EET-2EEST,M3.5.0/3,M10.5.0/4" },
            { name: "Europe/Zurich", value: "Europe/Zurich%CET-1CEST,M3.5.0,M10.5.0/3" },
        ]
    },
    {
        label: "Indian",
        items: [
            { name: "Indian/Antananarivo", value: "Indian/Antananarivo%EAT-3" },
            { name: "Indian/Chagos", value: "Indian/Chagos%<+06>-6" },
            { name: "Indian/Christmas", value: "Indian/Christmas%<+07>-7" },
            { name: "Indian/Cocos", value: "Indian/Cocos%<+0630>-6:30" },
            { name: "Indian/Comoro", value: "Indian/Comoro%EAT-3" },
            { name: "Indian/Kerguelen", value: "Indian/Kerguelen%<+05>-5" },
            { name: "Indian/Mahe", value: "Indian/Mahe%<+04>-4" },
            { name: "Indian/Maldives", value: "Indian/Maldives%<+05>-5" },
            { name: "Indian/Mauritius", value: "Indian/Mauritius%<+04>-4" },
            { name: "Indian/Mayotte", value: "Indian/Mayotte%EAT-3" },
            { name: "Indian/Reunion", value: "Indian/Reunion%<+04>-4" },
        ]
    },
    {
        label: "Pacific",
        items: [
            { name: "Pacific/Apia", value: "Pacific/Apia%<+13>-13" },
            { name: "Pacific/Auckland", value: "Pacific/Auckland%NZST-12NZDT,M9.5.0,M4.1.0/3" },
            { name: "Pacific/Bougainville", value: "Pacific/Bougainville%<+11>-11" },
            { name: "Pacific/Chatham", value: "Pacific/Chatham%<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45" },
            { name: "Pacific/Chuuk", value: "Pacific/Chuuk%<+10>-10" },
            { name: "Pacific/Easter", value: "Pacific/Easter%<-06>6<-05>,M9.1.6/22,M4.1.6/22" },
            { name: "Pacific/Efate", value: "Pacific/Efate%<+11>-11" },
            { name: "Pacific/Enderbury", value: "Pacific/Enderbury%<+13>-13" },
            { name: "Pacific/Fakaofo", value: "Pacific/Fakaofo%<+13>-13" },
            { name: "Pacific/Fiji", value: "Pacific/Fiji%<+12>-12" },
            { name: "Pacific/Funafuti", value: "Pacific/Funafuti%<+12>-12" },
            { name: "Pacific/Galapagos", value: "Pacific/Galapagos%<-06>6" },
            { name: "Pacific/Gambier", value: "Pacific/Gambier%<-09>9" },
            { name: "Pacific/Guadalcanal", value: "Pacific/Guadalcanal%<+11>-11" },
            { name: "Pacific/Guam", value: "Pacific/Guam%ChST-10" },
            { name: "Pacific/Honolulu", value: "Pacific/Honolulu%HST10" },
            { name: "Pacific/Kiritimati", value: "Pacific/Kiritimati%<+14>-14" },
            { name: "Pacific/Kosrae", value: "Pacific/Kosrae%<+11>-11" },
            { name: "Pacific/Kwajalein", value: "Pacific/Kwajalein%<+12>-12" },
            { name: "Pacific/Majuro", value: "Pacific/Majuro%<+12>-12" },
            { name: "Pacific/Marquesas", value: "Pacific/Marquesas%<-0930>9:30" },
            { name: "Pacific/Midway", value: "Pacific/Midway%SST11" },
            { name: "Pacific/Nauru", value: "Pacific/Nauru%<+12>-12" },
            { name: "Pacific/Niue", value: "Pacific/Niue%<-11>11" },
            { name: "Pacific/Norfolk", value: "Pacific/Norfolk%<+11>-11<+12>,M10.1.0,M4.1.0/3" },
            { name: "Pacific/Noumea", value: "Pacific/Noumea%<+11>-11" },
            { name: "Pacific/Pago_Pago", value: "Pacific/Pago_Pago%SST11" },
            { name: "Pacific/Palau", value: "Pacific/Palau%<+09>-9" },
            { name: "Pacific/Pitcairn", value: "Pacific/Pitcairn%<-08>8" },
            { name: "Pacific/Pohnpei", value: "Pacific/Pohnpei%<+11>-11" },
            { name: "Pacific/Port_Moresby", value: "Pacific/Port_Moresby%<+10>-10" },
            { name: "Pacific/Rarotonga", value: "Pacific/Rarotonga%<-10>10" },
            { name: "Pacific/Saipan", value: "Pacific/Saipan%ChST-10" },
            { name: "Pacific/Tahiti", value: "Pacific/Tahiti%<-10>10" },
            { name: "Pacific/Tarawa", value: "Pacific/Tarawa%<+12>-12" },
            { name: "Pacific/Tongatapu", value: "Pacific/Tongatapu%<+13>-13" },
            { name: "Pacific/Wake", value: "Pacific/Wake%<+12>-12" },
            { name: "Pacific/Wallis", value: "Pacific/Wallis%<+12>-12" },
        ]
    },
    {
        label: "Etc",
        items: [
            { name: "Etc/GMT", value: "Etc/GMT%GMT0" },
            { name: "Etc/GMT-0", value: "Etc/GMT-0%GMT0" },
            { name: "Etc/GMT-1", value: "Etc/GMT-1%<+01>-1" },
            { name: "Etc/GMT-2", value: "Etc/GMT-2%<+02>-2" },
            { name: "Etc/GMT-3", value: "Etc/GMT-3%<+03>-3" },
            { name: "Etc/GMT-4", value: "Etc/GMT-4%<+04>-4" },
            { name: "Etc/GMT-5", value: "Etc/GMT-5%<+05>-5" },
            { name: "Etc/GMT-6", value: "Etc/GMT-6%<+06>-6" },
            { name: "Etc/GMT-7", value: "Etc/GMT-7%<+07>-7" },
            { name: "Etc/GMT-8", value: "Etc/GMT-8%<+08>-8" },
            { name: "Etc/GMT-9", value: "Etc/GMT-9%<+09>-9" },
            { name: "Etc/GMT-10", value: "Etc/GMT-10%<+10>-10" },
            { name: "Etc/GMT-11", value: "Etc/GMT-11%<+11>-11" },
            { name: "Etc/GMT-12", value: "Etc/GMT-12%<+12>-12" },
            { name: "Etc/GMT-13", value: "Etc/GMT-13%<+13>-13" },
            { name: "Etc/GMT-14", value: "Etc/GMT-14%<+14>-14" },
            { name: "Etc/GMT0", value: "Etc/GMT0%GMT0" },
            { name: "Etc/GMT+0", value: "Etc/GMT+0%GMT0" },
            { name: "Etc/GMT+1", value: "Etc/GMT+1%<-01>1" },
            { name: "Etc/GMT+2", value: "Etc/GMT+2%<-02>2" },
            { name: "Etc/GMT+3", value: "Etc/GMT+3%<-03>3" },
            { name: "Etc/GMT+4", value: "Etc/GMT+4%<-04>4" },
            { name: "Etc/GMT+5", value: "Etc/GMT+5%<-05>5" },
            { name: "Etc/GMT+6", value: "Etc/GMT+6%<-06>6" },
            { name: "Etc/GMT+7", value: "Etc/GMT+7%<-07>7" },
            { name: "Etc/GMT+8", value: "Etc/GMT+8%<-08>8" },
            { name: "Etc/GMT+9", value: "Etc/GMT+9%<-09>9" },
            { name: "Etc/GMT+10", value: "Etc/GMT+10%<-10>10" },
            { name: "Etc/GMT+11", value: "Etc/GMT+11%<-11>11" },
            { name: "Etc/GMT+12", value: "Etc/GMT+12%<-12>12" },
            { name: "Etc/UCT", value: "Etc/UCT%UTC0" },
            { name: "Etc/UTC", value: "Etc/UTC%UTC0" },
            { name: "Etc/Greenwich", value: "Etc/Greenwich%GMT0" },
            { name: "Etc/Universal", value: "Etc/Universal%UTC0" },
            { name: "Etc/Zulu", value: "Etc/Zulu%UTC0" }
        ]
    }
];